# Generated by Django 3.2.9 on 2022-07-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rithual_app', '0003_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='font',
            field=models.CharField(blank=True, choices=[('З', 'Звичайний'), ('К', 'Курсив'), ('Ж', 'Жирний'), ('ЖК', 'Жирний курсив')], default='З', help_text='курсив, жирний, звичайний, жирний курсив', max_length=20, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_site',
            field=models.TextField(default='Сайт ритуальних послуг', verbose_name='Опис'),
        ),
    ]
