# Generated by Django 3.2.9 on 2022-07-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rithual_app', '0005_mainpage_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='picture',
            field=models.TextField(default='https://viyar.ua/ua/catalog/zaglushka_dlya_provodov_seraya_svetlaya/', verbose_name='Посилання на фото'),
        ),
    ]
