# Generated by Django 3.2.9 on 2022-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rithual_app', '0006_about_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.TextField(default='https://hafeleshop.com.ua/uploads/shop/products/main/02205340_0.jpg', verbose_name='Посилання на фото'),
        ),
    ]
