# Generated by Django 3.2.9 on 2022-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rithual_app', '0007_alter_about_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='header_image',
            field=models.TextField(default='https://service.muzychenko.dev/wp-content/uploads/2022/05/ritual1.webp', verbose_name='Зображення заголовка'),
        ),
    ]
