# Generated by Django 3.2.9 on 2022-08-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rithual_app', '0008_mainpage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rithualservices',
            name='how_display_description',
            field=models.CharField(blank=True, choices=[('Т', 'Текст'), ('С', 'Список')], default='Т', help_text='Текст або список', max_length=50, verbose_name='Відображення'),
        ),
    ]
