# Generated by Django 3.2.9 on 2022-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rithual_app', '0009_rithualservices_how_display_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('image', models.TextField(verbose_name='Зображення шапки сайта')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Зображення шапки сайта',
                'verbose_name_plural': 'Зображення шапки сайта',
            },
        ),
    ]
