# Generated by Django 3.2.9 on 2022-10-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rithual_app', '0011_auto_20220807_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mails', models.EmailField(max_length=255, verbose_name='Пошта')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='our_address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ваша адреса'),
        ),
    ]
